<?php

namespace AppBundle\Repository;

use Gedmo\Tree\Traits\Repository\ORM\NestedTreeRepositoryTrait;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends NestedTreeRepository
{

    public function getRootPost()
    {
        $q = $this->createQueryBuilder('p');
        $q
            ->where('p.lvl = 0')
            ->orderBy('p.created_at', 'DESC')
        ;

        return $q->getQuery()->getResult();
    }
}
