imports:
    - { resource: config.yml }

parameters:
    site: 'http://localhost:8000'

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    delivery_address: 'sebastien.kalinine@gmail.com'
    transport: gmail
    username:  "%mailer_user%"
    password:  "%mailer_password%"
