imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: extensions.yml }
    - { resource: fosuser/ }
    - { resource: easyadmin/ }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    project_name:       'Inédits'
    # directories
    avatar_directory:   '%kernel.root_dir%/../web/uploads/avatar'
    cover_directory:    '%kernel.root_dir%/../web/uploads/cover'
    post_directory:     '%kernel.root_dir%/../web/uploads/post'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets:
        packages:
            js:
               base_path: '/dist/js'
            css:
               base_path: '/dist/css'
            media:
               base_path: '/dist/media'
            avatar:
               base_path: '/uploads/avatar'
            cover:
               base_path: '/uploads/cover'
            default:
               base_path: '/dist/media/default'
            post:
               base_path: '/uploads/post'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
       resources: ['bootstrap_3_layout.html.twig']
    globals:
        project_name: "%project_name%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        mappings:
            gedmo_tree:
                type: yml
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: Post # (optional) it will default to the name set for the mapping
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# vich_uploader:
#     db_driver: orm
#     mappings:
#         avatar_file:
#             uri_prefix:         /uploads/avatar
#             upload_destination: %kernel.root_dir%/../web/uploads/avatar
        # cover:
        #     uri_prefix:         /uploads/cover
        #     upload_destination: %kernel.root_dir%/../web/uploads/cover
