AppBundle\Entity\Post:
    type: entity
    table: post
    repositoryClass: AppBundle\Repository\PostRepository
    # repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    gedmo:
        tree:
            type: nested
    manyToOne:
        root:
            targetEntity: AppBundle\Entity\Post
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeRoot
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
        parent:
            targetEntity: AppBundle\Entity\Post
            inversedBy: children
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: AppBundle\Entity\Post
            mappedBy: parent
            orderBy:
                lft: ASC
    manyToMany:
        users:
            targetEntity: AppBundle\Entity\User
            inversedBy: trees
            joinTable:
                name: post_user
            joinColumns:
                - joinColumn:
                    name: root_id
                    referencedColumnName: root
                - inversedJoinColumn:
                    name: user_id
                    referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
            nullable: true
        contentPlain:
            type: text
            nullable: true
            column: content_plain
        file:
            type: string
            length: 255
            nullable: true
        isMain:
            type: boolean
            options:
                default: 0
            column: is_main
        isEnd:
            type: boolean
            options:
                default: 0
            column: is_end
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
            - treeRight
        lvl:
            type: integer
            gedmo:
                - treeLevel
        slug:
            type: string
            length: '255'
            unique: true
            gedmo:
                slug:
                    separator: -
                    fields:
                        - title
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: "create"
            column: created_at
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: "update"
            column: updated_at
    lifecycleCallbacks: {  }
