AppBundle\Entity\Post:
    type: entity
    table: post
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    gedmo:
        tree:
            type: nested
    manyToOne:
        root:
            targetEntity: AppBundle\Entity\Post
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
            - treeRoot
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: posts
            joinColumn:
                name: user_id
                referencedColumnName: id
        parent:
            targetEntity: AppBundle\Entity\Post
            inversedBy: children
            joinColumn:
                referencedColumnName: id
                onDelete: CASCADE
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: AppBundle\Entity\Post
            mappedBy: parent
            orderBy:
                lft: ASC
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
            nullable: true
        isMain:
            type: boolean
            nullable: true
            column: is_main
        isEnd:
            type: boolean
            nullable: true
            column: is_end
        userId:
            type: integer
            column: user_id
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
            - treeRight
        lvl:
            type: integer
            gedmo:
                - treeLevel
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    separator: -
                    fields:
                        - title
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: "create"
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: "update"
    lifecycleCallbacks: {  }
