AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    oneToOne:
        user_profile:
            targetEntity: AppBundle\Entity\UserProfile
            joinColumn: profileId
            referencedColumnName: id
            cascade:
                - persist
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        profileId:
            type: integer
    lifecycleCallbacks: {  }
