AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: AppBundle\Repository\UserRepository
    manyToMany:
        trees:
            targetEntity: AppBundle\Entity\Post
            mappedBy: users
    oneToMany:
        posts:
            targetEntity: AppBundle\Entity\Post
            mappedBy: user
    oneToOne:
        user_profile:
            targetEntity: AppBundle\Entity\UserProfile
            inversedBy: user
            joinColumn: profileId
            referencedColumnName: id
            cascade:
                - persist
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    separator: -
                    fields:
                        - firstName
                        - lastName
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: "create"
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: "update"
    lifecycleCallbacks: {  }
