AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: AppBundle\Repository\UserRepository
    manyToMany:
        trees:
            targetEntity: AppBundle\Entity\Post
            mappedBy: users
    oneToMany:
        posts:
            targetEntity: AppBundle\Entity\Post
            mappedBy: user
    oneToOne:
        userProfile:
            targetEntity: AppBundle\Entity\UserProfile
            inversedBy: user
            joinColumn:
                name: profile_id
                nullable: false
            cascade:
                - persist
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        postCount:
            type: integer
            column: post_counts
            options:
                unsigned: true
        slug:
            type: string
            length: 255
            unique: true
            gedmo:
                slug:
                    separator: -
                    fields:
                        - firstName
                        - lastName
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: "create"
            column: created_at
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: "update"
            column: updated_at
    lifecycleCallbacks: {  }
