AppBundle\Entity\UserProfile:
    type: entity
    table: user_profile
    repositoryClass: AppBundle\Repository\UserProfileRepository
    oneToOne:
        user:
            targetEntity: AppBundle\Entity\User
            mappedBy: userProfile
            cascade:
                - remove
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        avatar:
            type: string
            length: 255
            nullable: true
        cover:
            type: string
            length: 255
            nullable: true
        facebook:
            type: string
            length: 255
            nullable: true
        twitter:
            type: string
            length: 255
            nullable: true
        website:
            type: string
            length: 255
            nullable: true
        biographie:
            type: text
            nullable: true
        favoriteBook:
            type: string
            length: 255
            nullable: true
            column: favorite_book
        favoriteAuthors:
            type: string
            length: 255
            nullable: true
            column: favorite_auhors
        favoriteGenre:
            type: string
            length: 255
            nullable: true
            column: favorite_genre
        inspiration:
            type: string
            length: 255
            nullable: true
        style:
            type: string
            length: 255
            nullable: true
        experience:
            type: text
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: "create"
            column: created_at
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: "update"
            column: updated_at
    lifecycleCallbacks: {  }
