liip_imagine :

    # configure resolvers
    resolvers :

        # setup the default resolver
        default :

            # use the default web path
            web_path : ~

    # your filter sets are defined here
    filter_sets :
            cache : ~

            user_avatar_sm:
                filters :
                    thumbnail  : { size : [50, 50], mode : outbound }
            user_cover_sm:
                filters :
                    thumbnail  : { size : [400, 200], mode : outbound }