AppBundle\Entity\Post:
    properties:
        title:
            - NotBlank: ~
            - Type:
                type: string
                message: Incorrect
        content:
            - Type:
                type: string
                message: Incorrect
        gtu:
            - NotNull:
                groups: [edit]
                message: Vous devez accepter les conditions générales d'utilisation
            - NotBlank:
                groups: [edit]
                message: Vous devez accepter les conditions générales d'utilisation
        file:
            - File:
                groups: [edit]
                mimeTypes: [text/plain, text/html]
                mimeTypesMessage: Format invalide


