AppBundle\Entity\Post:
    properties:
        title:
            - NotBlank: ~
            - Type:
                type: string
                message: Incorrect
        content:
            - NotBlank: ~
            - Type:
                type: string
                message: Incorrect
        gtu:
            - NotNull:
                message: Vous devez accepter les conditions générales d'utilisation
            - NotBlank:
                message: Vous devez accepter les conditions générales d'utilisation


