AppBundle\Entity\User:
    properties:
        firstName:
            - Type:
                type: string
                message: Incorrect
        lastName:
            - Type:
                type: string
                message: Incorrect
